### ISSUE TITLE
question / info: encore native 

### ISSUE THREAD

**Issue by m-vo** [terminal42/contao-asset-reload#1]
Hi, just stumbled across this bundle. Is the intent to allow HMR in dev or does it something else? :smile: 

----

Just for the record, I got HMR in encore to work (`yarn ecore dev-server --hot`) when disabling CSS extraction and adding some dev server config. 

```JS
let Encore = require('@symfony/webpack-encore');

// ...

if (Encore.isDevServer()) {
    Encore.disableCssExtraction()
}

const webpackConfig = Encore.getWebpackConfig();

webpackConfig.devServer = {
    host: '127.0.0.1',
    port: 8080,
    headers: {'Access-Control-Allow-Origin': '*'},
    disableHostCheck: true
};

module.exports = webpackConfig;
```

**Comment by aschempp** [comment]
🤷‍♂ not sure anymore, it's quite old and was only a test project. Maybe your solution was not available in encore back in the days.

**Comment by m-vo** [comment]
Allright :wink:.

At least the `Encore.disableCssExtraction()` thing is quite new.
